DATA:
  BATCH_SIZE: 32
  IMG_SIZE:
  - 240
  - 384
  ORI_SMOOTH_FACTOR: 3
  OTHER_AUGMENT: true
  PATH: ../datasets/speedPlus
  POS_SMOOTH_FACTOR: 100
  ROT_AUGMENT: true
  SHUFFLE: true
MODEL:
  BACKBONE:
    NAME: mobilenet_v2_pytorch
    RESIDUAL: true
  HEAD:
    KEYPOINTS_PATH: models/3d_models/tangoPoints.mat
    NAME: ursonet_pytorch
    N_ORI_BINS_PER_DIM: 12
    N_POS_BINS_PER_DIM: 10
    ORI: classification
    ORI_DELETE_UNUSED_BINS: false
    POS: regression
  MANUAL_COPY: true
  PRETRAINED_PATH: null
  QUANTIZATION: false
TRAIN:
  CLIP_BATCHNORM: false
  DECAY: 0.0
  GAMMA: 0.1
  LR: 0.01
  MILESTONES:
  - 35
  - 45
  MOMENTUM: 0.9
  N_EPOCH: 50
  OPTIM: SGD
  SCHEDULER: MultiStepLR
